# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Lint Checks

on:
  pull_request:
    branches: '**'

jobs:
  tests:
    name: flutter analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          
      - name: Flutter version
        run: flutter --version
      
      - name: Install packages
        run: flutter pub get
        
      - name: Generate files
        run: flutter pub run build_runner build --delete-conflicting-outputs
        
      - name: Analyze
        run: flutter analyze > flutter_analyze_report.txt

      - name: Comment PR
        if: ${{ failure() }} || ${{ success() }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: flutter_analyze_report.txt
