name: Lint Checks

on:
  pull_request:
    branches: '**'

concurrency:
  group: review-${{ github.base_ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  review-flutter-pr:
    name: Review Flutter PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: Install packages
        run: flutter pub get
        
      - name: Generate
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze
        run: flutter analyze > flutter_analyze_report.txt
        
      - name: Comment PR
        if: ${{ failure() }} || ${{ success() }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: flutter_analyze_report.txt
